// Generated by build/gen.py.

#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_

#define LAST_COMMIT_POSITION_NUM 2354
#define LAST_COMMIT_POSITION "2354 (6e8dcdebbadf)"

#endif  // OUT_LAST_COMMIT_POSITION_H_
